name    'puppet-jenkins_security'
version '0.1.0'
project_page 'https://github.com/openstack-hyper-v/puppet-jenkins_security'
source 'https://github.com/openstack-hyper-v/puppet-jenkins_security'
author 'Tim Rogers'
license 'Apache License, Version 2.0'
summary 'A module for configuring Jenkins users and security'
description 'A module for configuring Jenkins users and security'

dependency 'glarizza/xmlsimple', '>=0.0.1'
dependency 'nrvale0/bcrypt ', '>=1.0.0'
